const PRODUCTS = [
  {
    id: 1,
    name: "Cold-Pressed Coconut Oil",
    category: "oils",
    price: 249,
    weight: "500 ml",
    badge: "Bestseller",
    emoji: "🥥",
    color: "#e8f5e1",
    accent: "#5a7c4a",
    description: "Wood-pressed from fresh coconuts, never refined or bleached. Rich in lauric acid for cooking, skin, and hair.",
    benefits: ["No heat processing", "High smoke point", "Unrefined & virgin"],
    ingredients: "100% fresh coconut"
  },
  {
    id: 2,
    name: "Cold-Pressed Groundnut Oil",
    category: "oils",
    price: 199,
    weight: "1 Litre",
    badge: null,
    emoji: "🫙",
    color: "#fdf3e3",
    accent: "#b07c3a",
    description: "Traditional wood-pressed groundnut oil with a rich, nutty aroma. Perfect for Indian cooking.",
    benefits: ["Wood-pressed", "Rich in Vit E", "Natural flavour"],
    ingredients: "100% groundnuts"
  },
  {
    id: 3,
    name: "Organic Ragi Flour",
    category: "grains",
    price: 129,
    weight: "500 g",
    badge: "Organic",
    emoji: "🌾",
    color: "#f0ebe2",
    accent: "#7a6040",
    description: "Stone-ground finger millet flour from certified organic farms. High in calcium and naturally gluten-free.",
    benefits: ["Certified organic", "Gluten-free", "High calcium"],
    ingredients: "Organic finger millet (ragi)"
  },
  {
    id: 4,
    name: "Whole Wheat Atta",
    category: "grains",
    price: 149,
    weight: "1 kg",
    badge: null,
    emoji: "🌿",
    color: "#f5f0e8",
    accent: "#8a7050",
    description: "Stone-milled whole wheat flour retaining the bran and germ for full nutritional benefit.",
    benefits: ["Stone-milled", "Whole grain", "No maida blend"],
    ingredients: "100% whole wheat"
  },
  {
    id: 5,
    name: "Moringa Powder",
    category: "grains",
    price: 169,
    weight: "100 g",
    badge: "Superfood",
    emoji: "🍃",
    color: "#e5f0dc",
    accent: "#4a7a3a",
    description: "Shade-dried and cold-milled moringa leaves from South Indian farms. One of nature's most nutrient-dense foods.",
    benefits: ["Rich in iron", "High protein", "Cold-milled"],
    ingredients: "100% moringa leaves"
  },
  {
    id: 6,
    name: "Tulsi Green Tea",
    category: "beverages",
    price: 199,
    weight: "25 bags",
    badge: "New",
    emoji: "🍵",
    color: "#e8f5ec",
    accent: "#3a7a4a",
    description: "Delicate Darjeeling green tea blended with freshly dried holy basil (tulsi) for a calming, immunity-boosting cup.",
    benefits: ["No artificial flavour", "Caffeine moderate", "Immunity boost"],
    ingredients: "Green tea, tulsi leaves"
  },
  {
    id: 7,
    name: "Raw Ginger Honey",
    category: "sweeteners",
    price: 249,
    weight: "350 g",
    badge: "Raw",
    emoji: "🍯",
    color: "#fdf4dc",
    accent: "#c08a20",
    description: "Unprocessed forest honey infused with fresh ginger. Never heated above 40°C to preserve live enzymes.",
    benefits: ["Unheated raw honey", "Live enzymes", "Anti-inflammatory"],
    ingredients: "Raw honey, fresh ginger"
  },
  {
    id: 8,
    name: "Kokum Sharbat",
    category: "beverages",
    price: 149,
    weight: "500 ml",
    badge: null,
    emoji: "🫐",
    color: "#f0e5f5",
    accent: "#7a3a7a",
    description: "Traditional Konkan kokum concentrate — naturally cooling, digestive, and delightfully tart. Mix 1:5 with water.",
    benefits: ["Digestive", "No sugar added", "Traditional recipe"],
    ingredients: "Kokum extract, rock salt, jeera"
  },
  {
    id: 9,
    name: "Roasted Makhana",
    category: "snacks",
    price: 149,
    weight: "100 g",
    badge: "New",
    emoji: "✨",
    color: "#fef8ec",
    accent: "#b09050",
    description: "Lotus seeds roasted in desi ghee and lightly salted with Himalayan pink salt. A guilt-free crunchy snack.",
    benefits: ["High protein", "Low calorie", "Desi ghee roasted"],
    ingredients: "Makhana, ghee, Himalayan salt"
  },
  {
    id: 10,
    name: "Trail Mix — Forest",
    category: "snacks",
    price: 199,
    weight: "150 g",
    badge: null,
    emoji: "🌰",
    color: "#f0ece0",
    accent: "#6a5030",
    description: "A thoughtfully balanced mix of almonds, cashews, raisins, and dried cranberry — no added sugar or oil.",
    benefits: ["No added sugar", "No refined oil", "Natural energy"],
    ingredients: "Almonds, cashews, raisins, cranberry"
  },
  {
    id: 11,
    name: "A2 Desi Ghee",
    category: "oils",
    price: 299,
    weight: "250 g",
    badge: "Premium",
    emoji: "🧈",
    color: "#fffae8",
    accent: "#c09830",
    description: "Bilona-churned ghee from A2 milk of grass-fed Gir cows. Rich, aromatic, and prepared the traditional way.",
    benefits: ["Bilona method", "A2 milk only", "Grass-fed cows"],
    ingredients: "A2 cow milk (cultured butter)"
  },
  {
    id: 12,
    name: "Jaggery Powder",
    category: "sweeteners",
    price: 99,
    weight: "500 g",
    badge: null,
    emoji: "🟫",
    color: "#f5ecd8",
    accent: "#9a6030",
    description: "Pure cane jaggery powdered without any chemicals or anti-caking agents. A natural alternative to refined sugar.",
    benefits: ["No chemicals", "Iron-rich", "Low GI"],
    ingredients: "100% sugarcane jaggery"
  }
];
